# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               Sherrina
tagline:             '别紧张你这样能毕业'
description:         'this is a testing description'
description-backup:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 null
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              null
  url:               null
  email:             null

# Custom vars
version:             1.0.1

theme: jekyll-theme-cayman